package jdbc.program;

import java.sql.SQLException;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */

import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.List;

public class JFrameUtama extends javax.swing.JFrame {

    /**
     * Creates new form JFrameUtama
     */

    private MysqlMahasiswaService mhsService;
    private DefaultListModel<String> modelID;
    private DefaultListModel<String> modelNama;

    public JFrameUtama() {
        initComponents();

        this.setTitle("Aplikasi Data Mahasiswa");
        
        try {
            // Inisialisasi service dan model
            mhsService = new MysqlMahasiswaService();
            modelID = new DefaultListModel<>();
            modelNama = new DefaultListModel<>();
            
            // Set model ke JList
            jListID.setModel(modelID);
            jListNama.setModel(modelNama);
            
            // Clear default text fields
            clearFields();
            
            // Load data awal
            modelID.clear();
            modelNama.clear();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, 
                "Error koneksi database: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearFields() {
        textFieldNamaAdd.setText("");
        textFieldIdEdit.setText("");
        textFieldNamaEdit.setText("");
        textFieldIdHapus.setText("");
        textFieldNamaHapus.setText("");
    }

    private void refreshData() {
        try {
        // Ambil data dari database
            List<Mahasiswa> list = mhsService.getAll();
            // Clear model
            modelID.clear();
            modelNama.clear();
            // Tambahkan data ke model
            for (Mahasiswa mhs : list) {
                modelID.addElement(String.valueOf(mhs.getId()));
                modelNama.addElement(mhs.getNama());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                "Error mengambil data: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean validateInput(String nama) {
        if (nama == null || nama.trim().isEmpty()) {
            return false;
        }
        return true;
    }

    private boolean validateInputEdit(String id, String nama) {
        // Check if id and nama are not empty
        if (id == null || id.trim().isEmpty() || nama == null || nama.trim().isEmpty()) {
            return false;
        }
        
        // Check if id is numeric
        if (!id.matches("\\d+")) {
            return false;
        }
        
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListNama = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListID = new javax.swing.JList<>();
        jButtonData = new javax.swing.JButton();
        jLabelInput = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        textFieldNamaAdd = new java.awt.TextField();
        textFieldIdHapus = new java.awt.TextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        textFieldNamaHapus = new java.awt.TextField();
        jButtonHapus = new javax.swing.JButton();
        jButtonRiset = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        textFieldIdEdit = new java.awt.TextField();
        textFieldNamaEdit = new java.awt.TextField();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListNama.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListNama);

        jListID.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListID);

        jButtonData.setText("Ambil Semua Data");
        jButtonData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDataActionPerformed(evt);
            }
        });

        jLabelInput.setText("Nama : ");

        jLabelTitle.setText("Kelola Data Mahasiswa");

        textFieldNamaAdd.setText("textField1");
        textFieldNamaAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNamaAddActionPerformed(evt);
            }
        });

        textFieldIdHapus.setText("textField2");

        jButtonAdd.setText("tambahkan");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonEdit.setText("edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        textFieldNamaHapus.setText("textField2");

        jButtonHapus.setText("hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonRiset.setText("reset indeks");
        jButtonRiset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRisetActionPerformed(evt);
            }
        });

        jLabelID.setText("ID :");

        jLabelNama.setText("Nama : ");

        textFieldIdEdit.setText("textField2");

        textFieldNamaEdit.setText("textField2");
        textFieldNamaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNamaEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNama)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRiset)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldIdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNamaHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonData)
                            .addComponent(jLabelInput)
                            .addComponent(jLabelTitle)
                            .addComponent(textFieldNamaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNamaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonData)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNamaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonEdit)
                            .addComponent(textFieldIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNamaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textFieldIdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldNamaHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonHapus))
                        .addGap(20, 20, 20)
                        .addComponent(jButtonRiset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDataActionPerformed
        // TODO add your handling code here:
        try {
            modelID.clear();
            modelNama.clear();

            List<Mahasiswa> list = mhsService.getAll();

            for(Mahasiswa mhs : list) {
                modelID.addElement(String.valueOf(mhs.getId()));
                modelNama.addElement(mhs.getNama());
            }

        } catch (Exception e) {
             System.err.println("Error mengambil data: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonDataActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        try {
            String nama = textFieldNamaAdd.getText();
            if(validateInput(nama)) {
                Mahasiswa mhs = new Mahasiswa(0, nama);
                mhsService.add(mhs);
                clearFields();
                refreshData();
            }
        } catch (SQLException ex) {
            System.err.println("Error adding data: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        try {
            String idStr = textFieldIdEdit.getText();
            String nama = textFieldNamaEdit.getText();
            
            if(validateInputEdit(idStr, nama)) {
                int id = Integer.parseInt(idStr);
                Mahasiswa mhs = new Mahasiswa(id, nama);
                mhsService.update(mhs);
                clearFields();
                refreshData();
            }
        } catch (SQLException ex) {
            System.err.println("Error updating data: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        try {
            String idStr = textFieldIdHapus.getText();
            if(!idStr.trim().isEmpty() && idStr.matches("\\d+")) {
                int id = Integer.parseInt(idStr);
                mhsService.delete(id);
                clearFields();
                refreshData();
            }
        } catch (SQLException ex) {
            System.err.println("Error deleting data: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonRisetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRisetActionPerformed
        // TODO add your handling code here:
        try {
            mhsService.indexReset();
            refreshData();
        } catch (SQLException ex) {
            System.err.println("Error resetting index: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonRisetActionPerformed

    private void textFieldNamaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNamaAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNamaAddActionPerformed

    private void textFieldNamaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNamaEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNamaEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonData;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonRiset;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelInput;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JList<String> jListID;
    private javax.swing.JList<String> jListNama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    private java.awt.TextField textFieldIdEdit;
    private java.awt.TextField textFieldIdHapus;
    private java.awt.TextField textFieldNamaAdd;
    private java.awt.TextField textFieldNamaEdit;
    private java.awt.TextField textFieldNamaHapus;
    // End of variables declaration//GEN-END:variables
}
